### ISSUE TITLE
content view filter does not support module stream type

### ISSUE THREAD

**Issue by RJBJongejan** [RedHatSatellite/satellite-ansible-collection#32]
##### SUMMARY
It is not possible to create a content view filter to rhel8 module streams

According to the API docs (https://SATELLITE.EXAMPLE.COM/apidoc/v2/content_view_filters/create.html) creation of this filter is done by selecting type 'modulemd'. Also the original_module_streams param is currently not implemented

##### ISSUE TYPE
update content_view_filter.py with:
- add 'modulemd' to type
- add original_module_streams

**Comment by evgeni** [comment]
duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1872414
